# Generated by Django 4.1.7 on 2023-10-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curingapp', '0006_customuser_contact_no_customuser_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contact_no',
            new_name='Contact_no',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='project',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='site',
            new_name='Site',
        ),
    ]
