# Generated by Django 4.1.7 on 2023-10-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curingapp', '0007_rename_contact_no_customuser_contact_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curing_Image_Files',
            fields=[
                ('Curing_File_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Curing_File_Name', models.CharField(max_length=100)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curingapp.project_master')),
                ('Schedule_Curing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curingapp.schedule_curing')),
                ('Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curingapp.site_master')),
                ('Structural_Element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curingapp.structural_element')),
                ('Transaction_Concreting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curingapp.transaction_concreting')),
            ],
        ),
    ]
